---
- name: install nginx repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: default nginx config
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: allow nginx to connect to proxy
  command: setsebool -P httpd_can_network_connect true

- name: Start and enable nginx service
  service:
    name: nginx
    enabled: yes
    state: started
