---
jb_licensing_server_user: jbserver
jb_licensing_server_group: jbserver
jb_licensing_server_download_url: https://download-cf.jetbrains.com/lcsrv/license-server-installer.zip
jb_licensing_server_install_base: /usr/local/jetbrains
jb_licensing_server_home: "{{ jb_licensing_server_install_base }}/license-server"
jb_licensing_server_virtualhost: ""
jb_licensing_server_listen_address: "0.0.0.0"
jb_licensing_server_context: "/"
jb_licensing_server_port: 8080
jb_licensing_server_stats_token: ""
jb_licensing_server_http_proxy_host: ""
jb_licensing_server_http_proxy_port: ""
